# Generated by Django 4.1.3 on 2022-11-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_habit_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='goal',
            new_name='calories',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='progress',
        ),
    ]
