# Generated by Django 4.1.3 on 2022-11-06 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_record_delete_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='goal',
        ),
        migrations.AddField(
            model_name='habit',
            name='metric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='habitrecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='habit.habit'),
        ),
    ]
