# Generated by Django 4.1.3 on 2022-11-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_remove_habit_calories_remove_habit_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
