# Generated by Django 4.1.3 on 2022-11-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0006_remove_record_user_record_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('habitrecord', 'date'), name='dailyrecord'),
        ),
    ]
